wheel_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - rf_wheel_joint
    - lf_wheel_joint
    - lb_wheel_joint
    - rb_wheel_joint

# gazebo_ros_control:
#   pid_gains:
#     rf_wheel_joint:
#       p: 0
#     lf_wheel_joint:
#       p: 0
#     lb_wheel_joint:
#       p: 0
#     rb_wheel_joint:
#       p: 0


# rf_wheel_joint_velocity_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: "rf_wheel_joint"

# lf_wheel_joint_velocity_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: "lf_wheel_joint"

# lb_wheel_joint_velocity_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: "lb_wheel_joint"

# rb_wheel_joint_velocity_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: "rb_wheel_joint"