uint8[] tables

uint8 DUAL_TABLE_UPPER = 0
uint8 DUAL_TABLE_LOWER = 1
uint8 MOVABLE_TABLE_1200 = 2
uint8 MOVABLE_TABLE_1500 = 3
uint8 MOVABLE_TABLE_1800 = 4
---
---
uint8 status

uint8 MOVING_TO_DUAL_TABLE = 0
uint8 SHOOTING_ON_DUAL_TABLE_UPPER = 1
uint8 SHOOTING_ON_DUAL_TABLE_LOWER = 2
uint8 MOVING_TO_MOVABLE_TABLE_1200 = 3
uint8 SHOOTING_ON_MOVABLE_TABLE_1200 = 4
uint8 MOVING_TO_MOVABLE_TABLE_1500 = 5
uint8 SHOOTING_ON_MOVABLE_TABLE_1500 = 6
uint8 MOVING_TO_MOVABLE_TABLE_1800 = 7
uint8 SHOOTING_ON_MOVABLE_TABLE_1800 = 8
uint8 MOVING_TO_HOME = 9