uint8[] tables

uint8 DUAL_TABLE_UPPER_F = 0
uint8 DUAL_TABLE_UPPER_R = 1
uint8 DUAL_TABLE_UPPER_B = 2
uint8 DUAL_TABLE_UPPER_L = 3
uint8 DUAL_TABLE_LOWER = 4
uint8 MOVABLE_TABLE_1200 = 5
uint8 MOVABLE_TABLE_1500 = 6
uint8 MOVABLE_TABLE_1800 = 7
---
---
uint8 phase
uint8 target
string status

uint8 MOVE = 0
uint8 ALIGN = 1
uint8 SHOOT = 2
uint8 BACK = 3

uint8 DUAL_TABLE_UPPER_F = 0
uint8 DUAL_TABLE_UPPER_R = 1
uint8 DUAL_TABLE_UPPER_B = 2
uint8 DUAL_TABLE_UPPER_L = 3
uint8 DUAL_TABLE_LOWER = 4
uint8 MOVABLE_TABLE_1200 = 5
uint8 MOVABLE_TABLE_1500 = 6
uint8 MOVABLE_TABLE_1800 = 7
uint8 HOME = 8