local_costmap:
  global_frame: odom
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.1
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: map

  # inflation_layer:
  #   inflation_radius: 0.2